# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuetracker', '0002_auto_20180612_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='submitter',
        ),
        migrations.AddField(
            model_name='ticket',
            name='solver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Solverdsd', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
