# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0003_auto_20180613_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
