# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0004_auto_20180612_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('title',)},
        ),
    ]
