# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_auto_20180613_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='issuetracker.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closeddate',
            field=models.DateTimeField(null=True, verbose_name='Closed date'),
        ),
    ]
