# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0005_auto_20180612_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='issuetracker.Category'),
        ),
    ]
