# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0006_auto_20180613_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='closeddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed date'),
        ),
    ]
