# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0007_auto_20180612_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='solver',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Solver', to=settings.AUTH_USER_MODEL),
        ),
    ]
