# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-12 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0009_auto_20180612_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='submitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Submitter', to=settings.AUTH_USER_MODEL),
        ),
    ]
